apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namesapce: san-shuttle-dev
spec:
  securityContext:
    runAsUser: 0
  serviceAccount: kaniko
  containers:
  - name: kaniko
    image: registry.global.ccc.srvb.can.paas.cloudcenter.corp/san-devops-san/kaniko-executor:debug
    imagePullPolicy: Always
    resources:
      limits:
        memory: "1Gi"
        cpu: "400m"
      requests:
        memory: "1Gi"
        cpu: "400m"
    command:
    - /busybox/cat
    env:
      - name: http_proxy
        value: http://proxyapps.gsnet.corp:80
      - name: https_proxy
        value: http://proxyapps.gsnet.corp:80
      - name: no_proxy
        value: .corp
    tty: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker      
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: kanikobuildershuttle
          items:
            - key: .dockerconfigjson
              path: config.json